### PR TITLE
Bug fix for bypass_routing_option = 'direct_to_outlet' method

### LINKED ISSUE #54: Update cime directory in buildlib and buildnml
The path for cime tools was changed from cime/script/Tools to cime/CIME/Tools in cime6.0.17. This path is also set in buildlib and buildnml and should be updated. cime magic allows this to work as it is, but to prevent the confusion of setting to a directory that doesn't exist, to allow these scripts to be run outside a case, and to prevent future problems this should be updated.

### LINKED ISSUE #56: Some issues with direct_to_outlet option
bypass_routing_option=direct_to_outlet has some issues with budget warnings. We haven't actually tested this option until very recently because of issues in the CESM system with bringing MOM in.

See this comment in a CTSM issue on negative runoff:

https://github.com/ESCOMP/CTSM/issues/1816#issuecomment-1222528679

@olyson

### PR DESCRIPTION
**Pull request by olyson**
This fixes the balance errors evident in the mosart log file when the bypass_routing_option='direct_to_outlet' method is used.
Note that these balance errors are warnings and do not stop the model.
Code from @swensosc 
PR requested by @ekluzek 

Fixes #54 
Fixes #56 

Test case:
/glade/work/oleson/ctsm5.1.dev100/cime/scripts/ctsm51_ctsm51d100_1deg_GSWP3V1_directtooutlet_2000
Note that the test case uses ctsm5.1.dev100 and mosart1_0_45.
Verified that there were no balance errors in the mosart log file.
Testing: Standard mosart test list on cheyenne PASS with expected change in answers for
ERP_D.f10_f10_mg37.I1850Clm50Bgc.cheyenne_intel.mosart-qgrwlOpts

Also don't allow the threshold option to be set with
direct_to_outlet is choosen, as well as any option other
than "all" for "none".

Answers change when direct_to_outlet option is used

### CODE REVIEW

**Comment by ekluzek** [comment]
@olyson does this have everything needed in place? Naoki tried using this branch and was still seeing trouble with direct_to_outlet method for MOSART.

**Comment by olyson** [comment]
My understanding from Sean is that these two things need to be set in the mosart namelist:

bypass_routing_option = 'direct_to_outlet'
qgwl_runoff_option = 'negative'

**Comment by swensosc** [comment]
The 'negative' option bypasses the routing model, and sends all negative runoff  either directly to the coupler, or to the river mouth (which then goes to the coupler).  The 'threshold' option does the additional step of first checking the amount of water in the routing model locally.  If there is available water (above a specified threshold, hence the name), that water is used to offset some of the negative runoff.  This acts to reduce the amount of negative runoff that is passed to the coupler.  That is effectively what is happening in the 'direct_to_outlet' method anyway, so it seems like it would be unnecessary for the 'direct_to_outlet' option.

**Comment by swensosc** [comment]
I thought the 'threshold' option was only implemented for the
'direct_in_place' option (?)

**Comment by ekluzek** [comment]
Perfect that's what I needed to know. I'll disable setting it for anything but direct_i_place.

**Comment by ekluzek** [comment]
Note this changes answers for the test case: ERP_D.f10_f10_mg37.I1850Clm50Bgc.cheyenne_intel.mosart-qgrwlOpts

```
 RMS rofImp_Forr_rofi                 3.8131E-06            NORMALIZED  3.2797E+01
 RMS rofImp_Forr_rofl                 8.2276E-06            NORMALIZED  3.6195E+00
```

My guess is that everything else will be identical

**Comment by ekluzek** [comment]
The ERS_Ld5.f10_f10_mg37.I2000Clm50BgcCru.cheyenne_intel.mosart-iceOff test is exact and I expect all other tests will be as well.

**Pull request merged**
