### PR TITLE
bring in nuopc cap 

### PR DESCRIPTION
**Pull request by mvertens**
This PR brings in the NUOPC cap addition into master. New mosart baselines were created on izumi and the following tests were run:

./create_test --xml-category mosart --xml-machine hobart --compare mosart1_0_33_ctsm1.0.dev049 

The tests passed and the results were bfb. Note that only the mct tests were run here. Future tests will include the nuopc cap.

### CODE REVIEW

**Comment by mvertens** [comment]
@ekluzek - could you please let me know when this PR will be merged in. I believe I have done all of the relevant testing and it does not effect the mct answers. This is really needed for the high-priority NUOPC work that is ongoing.

**Comment by ekluzek** [comment]
OK, sorry. I have been looking at this. I might have some changes to request, and/or may need to ask you some questions. So I'll get back to you again by this afternoon.

**Comment by mvertens** [comment]
Thanks. This code does not need a code review in my opinion. I have also
gone over these changes previously with @billsacks and he was fine with the
changes. What is needed is verification that enough testing was done and
that the PR can then be merged.

**Comment by ekluzek** [comment]
It's also good to do code reviews with more people. But, I do think you can see that your doing a code review with Bill doesn't help me to understand the changes. I thought the changes might be just in adding new code to nuopc, but there's also changes on the MCT side. It's helpful for me to understand what's going on there.

But, I've gone through and figured it out and updated the ChangeLog now.

**Comment by mvertens** [comment]
The changes were needed since the model code was referencing cap code -
which should never happen. The same changes will be brought into the rtm PR
that will be coming soon.

**Comment by mvertens** [comment]
I think this is a worthwhile goal. Moving forwards - once we get all of the
nuopc caps into place we can see if it makes sense to do this. However, as
you noted there is very little overlap.

**Comment by mvertens** [comment]
This is very easily doable. We just add --driver nuopc to create_test. I
agree that this is a good thing to do.

**Comment by mvertens** [comment]
I am doing this in all of my testing.

**Comment by ekluzek** [comment]
In order to ensure that both the mct cap and nuopc caps are tested, there should be a testmods_dirs/mosart/nuopcCAP directory added that has a include_user_mods that starts from "../default" and then adds a shell_commands file with

`./xmlchange COMP_INTERFACE=nuopc`

Then we know the nuopc cap is tested every time standard testing is run.

**Comment by mvertens** [comment]
No - I do not think this is needed. Otherwise you are simply duplicating
tests. You simply need to invoked your create_test with an optional input
of --driver nuopc.

**Comment by ekluzek** [comment]
OK, I think we need to talk about this in person then -- because, that makes no sense to me. I'm not going to know I need to run create_test both with and without --driver nuopc. And running the full test list with both drivers means you are duplicating ALL tests for both drivers. So how is that duplicating tests? I'm going to assume I just need one extra test with the nuopc driver.

**Comment by mvertens** [comment]
You really do want to duplicate all the tests with the NUOPC caps - since
things are very different and this is only temporary as we migrate the
whole system to the nuopc cap. So its just a function of invoking the
create_test twice. Happy to talk more about this next week. And maybe with
the other CTSM SE's so that its not just pairwise communication.

**Comment by billsacks** [comment]
I agree pretty strongly with @ekluzek here.

**Comment by billsacks** [comment]
To elaborate... and thinking mostly about CTSM here: We'll want to make sure we regularly test the nuopc cap, but we really don't want to run the full test suite twice for every tag. We need some guidance on a minimal set of tests that is sufficient to cover all of the logic that is unique to the nuopc cap: there's no need to cover all of the myriad of options with both mct and nuopc, since most of the CTSM (and MOSART, RTM, etc.) code is the same whether you're using mct or nuopc.

**Comment by mvertens** [comment]
I agree. However, at the very beginning I think you probably want to do
that. I've caught very strange problems in running the whole test POP aux
suite with the mct and nuopc cap. It might be that you simply fire it off
as a sanity check and document things. Like I said - I think it would be
helpful to talk next week and all come to an agreement of the best way
forwards. However, I don't have the CISM cap fully working yet and have not
even come close to generating all the mesh files for CTSM - so this is not
a time critical issue to resolve.

**Comment by billsacks** [comment]
@mvertens good point that it's probably worth running the full test suites at least once with the nuopc cap.

**Pull request merged**
